// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  javaSidebar: [
    {type: 'autogenerated', dirName: 'java'},
  ],
  springbootSidebar: [
    {type: 'autogenerated', dirName: 'springboot'},
  ],
  pythonSidebar: [
    {type: 'autogenerated', dirName: 'python'},
  ],
  datastructuresSideBar: [
    {type: 'autogenerated', dirName: 'datastructures-algorithms'},
  ],
  dockerSidebar: [
    {type: 'autogenerated', dirName: 'docker'},
  ],
};

export default sidebars;